"use client";
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardReport } from "@/services/reports";
import { currency } from "@/lib/finance/client";
export const monthNames = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
export function ReportCharts({ trend }: { trend: DashboardReport["trend"] }) {
  const hasData = trend.some((r) => r.income !== "0.00" || r.expenses !== "0.00");
  const points = trend.map((r) => ({ ...r, label: `${monthNames[r.month - 1]}/${String(r.year).slice(-2)}`, income: Number(r.income), expenses: Number(r.expenses), netSavings: Number(r.netSavings) }));
  return <section className="panel report-chart"><h2>Evolução financeira</h2><p>Receitas, despesas e economia nos seis meses até o período selecionado.</p>{hasData ? <div className="chart-canvas"><ResponsiveContainer width="100%" height="100%" minWidth={0}><ComposedChart data={points} margin={{ top: 10, right: 10, bottom: 5, left: 0 }} accessibilityLayer><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10 }} interval={0} /><YAxis width={55} tick={{ fontSize: 10 }} tickFormatter={(n: number) => new Intl.NumberFormat("pt-BR", { notation: "compact" }).format(n)} /><Tooltip formatter={(value, name) => [new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value)), name]} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar isAnimationActive={false} name="Receitas" dataKey="income" fill="#235e4c" /><Bar isAnimationActive={false} name="Despesas" dataKey="expenses" fill="#b15a31" /><Line isAnimationActive={false} name="Economia líquida" dataKey="netSavings" stroke="#5554a1" strokeWidth={2} strokeDasharray="5 3" /></ComposedChart></ResponsiveContainer></div> : <p className="report-empty">Nenhuma receita ou despesa realizada nestes seis meses.</p>}<details><summary>Ver valores da evolução</summary><div className="report-table-wrap" tabIndex={0} role="region" aria-label="Valores da evolução financeira"><table className="report-table"><thead><tr><th>Mês</th><th>Receitas</th><th>Despesas</th><th>Economia</th></tr></thead><tbody>{trend.map((r) => <tr key={`${r.year}-${r.month}`}><th>{monthNames[r.month - 1]}/{r.year}</th><td>{currency(r.income)}</td><td>{currency(r.expenses)}</td><td>{currency(r.netSavings)}</td></tr>)}</tbody></table></div></details></section>;
}

