"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useForm, Controller, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus, Pencil, Trash2, Pause, Play } from "lucide-react";
import { financialRequest, currency, type CategoryRecord } from "@/lib/finance/client";
import { planningSchema, percentUnits, type PlanningInput } from "@/lib/validations/planning";
import { plannedPreview } from "@/lib/finance/planning-preview";
import { Feedback, Modal, Select } from "@/components/finance/controls";
import { MoneyField } from "@/components/finance/money-field";
import { RowActions } from "@/components/finance/transaction-actions";
import { useDiscard } from "@/components/finance/use-discard";
import { GroupForm } from "./group-form";
const empty: PlanningInput = { revision: 0, enabled: false, incomeSource: "REALIZED", referenceIncome: "0.00", groups: [] };
export function PlanningSettings() {
  const [categories, setCategories] = useState<CategoryRecord[]>([]), [realized, setRealized] = useState("0.00");
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  const [error, setError] = useState(""), [message, setMessage] = useState("");
  const [revision, setRevision] = useState(0), [editor, setEditor] = useState<number | "new" | null>(null), [removing, setRemoving] = useState<number | null>(null);
  const [dirty, setDirty] = useState(false), [reloadConfirm, setReloadConfirm] = useState(false);
  const { register, control, reset, setValue, handleSubmit, formState: { errors, isDirty } } = useForm<PlanningInput>({ resolver: zodResolver(planningSchema), defaultValues: empty });
  const draft = useWatch({ control }) as PlanningInput;
  const discard = useDiscard(dirty, () => { setEditor(null); setDirty(false); });
  useEffect(() => { const c = new AbortController(); Promise.all([financialRequest<{ data: PlanningInput }>("/api/planning", { signal: c.signal }), financialRequest<{ data: CategoryRecord[] }>("/api/categories?type=EXPENSE", { signal: c.signal }), financialRequest<{ data: { income: string } }>("/api/dashboard", { signal: c.signal })]).then(([p, cats, report]) => { if (!c.signal.aborted) { reset(p.data); setCategories(cats.data); setRealized(report.data.income); setLoaded(true); setError(""); } }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [revision, reset]);
  const groups = draft.groups ?? [];
  const total = groups.filter(g => g.active).reduce((sum,g) => sum + percentUnits(g.percentage), 0);
  const income = draft.incomeSource === "MANUAL" ? draft.referenceIncome : realized;
  const changeGroups = (next: PlanningInput["groups"]) => { const parsed = planningSchema.safeParse({ ...draft, referenceIncome: draft.incomeSource === "MANUAL" && !draft.referenceIncome ? "1.00" : draft.referenceIncome, groups: next }); if (!parsed.success) { setError(parsed.error.issues[0].message); return false; } setValue("groups", next, { shouldDirty: true }); setError(""); return true; };
  async function save(data: PlanningInput) { setBusy(true); setError(""); setMessage(""); try { const r = await financialRequest<{ data: PlanningInput }>("/api/planning", { method: "PUT", body: JSON.stringify(data) }); reset(r.data); setMessage("Planejamento salvo."); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  function reload() { setLoading(true); setRevision(v => v + 1); setReloadConfirm(false); }
  function open(index: number | "new") { setDirty(false); setError(""); setEditor(index); }
  const names = (ids: string[]) => ids.length > 3 ? `${ids.length} categorias` : ids.map(id => categories.find(c => c.id === id)?.name ?? "Categoria").join(" · ") || "Sem categorias";
  const actions = (index: number) => <RowActions description={groups[index].name} items={[{ label: "Editar", icon: Pencil, onSelect: () => open(index) }, { label: groups[index].active ? "Desativar" : "Ativar", icon: groups[index].active ? Pause : Play, onSelect: () => changeGroups(groups.map((g,i) => i === index ? { ...g, active: !g.active } : g)) }, { label: "Excluir", icon: Trash2, danger: true, onSelect: () => setRemoving(index) }]} />;
  const preview = (percentage: string) => { const amount = plannedPreview(income, percentage); return amount === null ? "—" : currency(amount); };
  return <div className="reports"><div className="page-heading"><div><span className="eyebrow">ESCOLHAS PARA O SEU MÊS</span><h1>Planejamento da renda</h1><p>Defina seus grupos, percentuais e alertas.</p></div><Link className="text-link" href="/dashboard">Voltar à visão mensal</Link></div><Feedback error={error || errors.referenceIncome?.message || errors.groups?.message} message={message} />{loading ? <p role="status">Carregando planejamento…</p> : !loaded ? <button className="button secondary" onClick={reload}>Tentar novamente</button> : <>
    <form noValidate onSubmit={handleSubmit(save)}><fieldset disabled={busy} className="form-fieldset"><section className="panel planning-base"><label className="checkbox-field"><input type="checkbox" {...register("enabled")} />Ativar planejamento da renda</label><Select id="planning-source" label="Fonte da renda" {...register("incomeSource")} onChange={e => { setValue("incomeSource", e.target.value as PlanningInput["incomeSource"], { shouldDirty: true }); if (e.target.value === "MANUAL" && draft.referenceIncome === "0.00") setValue("referenceIncome", "", { shouldDirty: true }); if (e.target.value === "REALIZED" && !draft.referenceIncome) setValue("referenceIncome", "0.00", { shouldDirty: true }); }}><option value="REALIZED">Renda realizada do mês</option><option value="MANUAL">Renda mensal informada</option></Select>{draft.incomeSource === "MANUAL" && <Controller name="referenceIncome" control={control} render={({ field }) => <MoneyField id="planning-income" label="Renda mensal de referência (R$)" {...field} onValueChange={field.onChange} error={errors.referenceIncome?.message} />} />}</section>
      <div className="planning-total"><span>Renda de referência: <strong>{preview("100")}</strong></span><span>Planejado: <strong>{(total / 100).toFixed(2).replace(".", ",")}%</strong></span><span>Disponível: <strong>{((10000-total)/100).toFixed(2).replace(".", ",")}%</strong></span></div>
      <div className="section-heading"><h2>Grupos</h2><button type="button" className="button secondary" disabled={groups.length >= 50} onClick={() => open("new")}><Plus size={16} />Adicionar grupo</button></div>
      <div className="ledger-desktop"><table className="ledger-table planning-ledger"><caption className="ledger-caption">Selecione um grupo para editar. Mudanças são aplicadas ao salvar o planejamento.</caption><thead><tr>{["Grupo", "Percentual", "Valor planejado", "Alerta", "Categorias", "Status", "Ações"].map(label => <th scope="col" key={label} className={label === "Valor planejado" ? "ledger-value" : undefined}>{label}</th>)}</tr></thead><tbody>{groups.map((g,i) => <tr key={i} onClick={() => open(i)}><td><button type="button" className="ledger-description" onClick={e => { e.stopPropagation(); open(i); }}><strong>{g.name}</strong></button></td><td>{g.percentage.replace(".", ",")}%</td><td className="ledger-value">{preview(g.percentage)}</td><td>{g.alertPercentage.replace(".", ",")}%</td><td>{names(g.categoryIds)}</td><td>{g.active ? "Ativo" : "Inativo"}</td><td><div className="ledger-actions">{actions(i)}</div></td></tr>)}</tbody></table></div>
      <ul className="ledger-mobile advanced-mobile" aria-label="Grupos do planejamento">{groups.map((g,i) => <li key={i}><button type="button" className="ledger-mobile-entry" onClick={() => open(i)}><strong className="ledger-mobile-title">{g.name}</strong><span>{g.percentage.replace(".", ",")}%</span><span className="ledger-mobile-date">{preview(g.percentage)} · Alerta {g.alertPercentage.replace(".", ",")}%</span><span className="ledger-mobile-date">{names(g.categoryIds)} · {g.active ? "Ativo" : "Inativo"}</span></button>{actions(i)}</li>)}</ul>{!groups.length && <p className="empty-state">Adicione seu primeiro grupo.</p>}
      <p className="report-note">Grupos inativos não entram no total planejado. A configuração orienta a renda e não cria movimentações financeiras.</p><div className="record-actions"><button type="button" className="button secondary" onClick={() => isDirty ? setReloadConfirm(true) : reload()}>Cancelar alterações</button><button className="button primary" disabled={busy}>{busy ? "Salvando…" : "Salvar planejamento"}</button></div>
    </fieldset></form>
  </>}
  {editor !== null && <Modal drawer dismissOutside title={editor === "new" ? "Novo grupo" : "Editar grupo"} onClose={discard.requestClose}><Feedback error={error} /><GroupForm initial={editor === "new" ? undefined : groups[editor]} categories={categories} used={groups.flatMap((g,i) => i !== editor && g.active ? g.categoryIds : [])} onDirty={setDirty} onCancel={discard.requestClose} onSave={g => { const next = editor === "new" ? [...groups,g] : groups.map((old,i) => i === editor ? g : old); if (changeGroups(next)) { setEditor(null); setDirty(false); setMessage("Grupo atualizado. Salve o planejamento para aplicar."); } }} /></Modal>}{discard.confirmation}
  {removing !== null && <Modal title="Excluir grupo?" onClose={() => setRemoving(null)}><p>Lançamentos e categorias serão preservados. A remoção será aplicada ao salvar o planejamento.</p><div className="record-actions"><button className="button secondary" onClick={() => setRemoving(null)}>Cancelar</button><button className="button danger" onClick={() => { changeGroups(groups.filter((_,i) => i !== removing)); setRemoving(null); }}>Excluir grupo</button></div></Modal>}
  {reloadConfirm && <Modal title="Descartar alterações?" onClose={() => setReloadConfirm(false)}><p>O planejamento será recarregado sem salvar as alterações.</p><div className="record-actions"><button className="button secondary" onClick={() => setReloadConfirm(false)}>Continuar editando</button><button className="button danger" onClick={reload}>Descartar alterações</button></div></Modal>}
  </div>;
}
