import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { formatDate } from "@/lib/utils/format";
import { LogoutButton } from "@/components/layout/logout-button";
export default async function Settings() {
  const user = await requireUser();
  return <><div className="page-heading"><div><span className="eyebrow">DO SEU JEITO</span><h1>Configurações</h1><p>Conheça sua conta e seu espaço pessoal.</p></div></div><section className="panel settings-panel"><h2>Planejamento da renda</h2><p>Distribua sua renda em grupos personalizados e acompanhe compromissos e alertas.</p><Link className="text-link" href="/configuracoes/planejamento">Configurar planejamento →</Link></section><section className="panel settings-panel"><h2>Categorias financeiras</h2><p>Personalize as categorias de receitas e despesas.</p><Link className="text-link" href="/configuracoes/categorias">Gerenciar categorias →</Link></section><section className="panel settings-panel"><h2>Minha conta</h2><dl><div><dt>Nome</dt><dd>{user.name}</dd></div><div><dt>E-mail</dt><dd>{user.email}</dd></div><div><dt>Conta criada em</dt><dd>{formatDate(user.createdAt)}</dd></div></dl><p className="muted">A edição de dados será disponibilizada em uma próxima fase.</p></section><section className="panel settings-panel"><h2>Meu espaço familiar</h2><dl><div><dt>Nome</dt><dd>{user.membership?.household.name ?? "Sem espaço vinculado"}</dd></div><div><dt>Seu papel</dt><dd>{user.membership?.role === "OWNER" ? "Proprietário" : user.membership ? "Membro" : "—"}</dd></div></dl><p className="muted">Convites para outras pessoas estarão disponíveis em breve.</p></section><section className="panel settings-panel"><h2>Sessão</h2><p className="muted">Encerre seu acesso neste navegador.</p><LogoutButton /></section></>;
}

