"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Plus, Trash2, Pencil, Check, Archive, RotateCcw, Plane, House, PiggyBank, Car, GraduationCap, Target } from "lucide-react";
import { useDiscard } from "@/components/finance/use-discard";
import { Field } from "@/components/ui/field";
import { Modal, Feedback, Select } from "@/components/finance/controls";
import { DateField } from "@/components/finance/date-field";
import { RowActions, type RowAction } from "@/components/finance/transaction-actions";
import { financialRequest, currency, type AccountRecord } from "@/lib/finance/client";
import { todayInBrazil, displayDate, displayCompetence } from "@/lib/finance/dates";
import type { GoalRecord, GoalContributionRecord } from "@/services/goals";
import { GoalProgress } from "./goal-progress";
import { GoalForm, ContributionForm, ParticipantForm } from "./goal-forms";
const statuses = { ACTIVE: "Ativa", COMPLETED: "Concluída", ARCHIVED: "Arquivada" };
const icons = { travel: Plane, home: House, reserve: PiggyBank, car: Car, study: GraduationCap };
type Editor = { kind: "goal" } | { kind: "contribution"; initial?: GoalContributionRecord } | { kind: "participant"; initial?: GoalRecord["participants"][number] };
type Result = { data: GoalRecord[]; pagination: { total: number; page: number; limit: number } };
export function GoalsManager() {
  const [result, setResult] = useState<Result>(), [accounts, setAccounts] = useState<AccountRecord[]>([]);
  const [query, setQuery] = useState(""), [page, setPage] = useState(1), [revision, setRevision] = useState(0);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [filtersOpen, setFiltersOpen] = useState(false);
  const [error, setError] = useState(""), [message, setMessage] = useState("");
  const [detail, setDetail] = useState<GoalRecord | null>(null), [editor, setEditor] = useState<Editor | null>(null);
  const [dirty, setDirty] = useState(false);
  const [confirmation, setConfirmation] = useState<{ title: string; description: string; url: string; method: string; body?: unknown; deleting?: boolean } | null>(null);
  const [actionError, setActionError] = useState("");
  const through = new URLSearchParams(query).get("through") ?? todayInBrazil();
  useEffect(() => {
    const controller = new AbortController();
    Promise.all([financialRequest<Result>(`/api/goals?${query}&page=${page}`, { signal: controller.signal }), financialRequest<{ data: AccountRecord[] }>("/api/accounts", { signal: controller.signal })]).then(([r, a]) => { if (!controller.signal.aborted) { setResult(r); setAccounts(a.data); setError(""); } }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [query, page, revision]);
  useEffect(() => { const id = new URLSearchParams(window.location.search).get("meta"); if (!id) return; const c = new AbortController(); financialRequest<{ data: GoalRecord }>(`/api/goals/${id}`, { signal: c.signal }).then(r => setDetail(r.data)).catch(e => { if (!c.signal.aborted) setError(e.message); }); return () => c.abort(); }, []);
  function refresh() { setLoading(true); setRevision(v => v + 1); }
  function close() { setDetail(null); setEditor(null); setDirty(false); setActionError(""); }
  const { requestClose, confirmation: discardConfirmation } = useDiscard(dirty, close);
  function edit(row: GoalRecord | null, next: Editor) { setDetail(row); setEditor(next); setDirty(false); setActionError(""); }
  async function saved() { const id = detail?.id; setEditor(null); setDirty(false); setMessage("Registro salvo com sucesso."); refresh(); if (id) { try { setDetail((await financialRequest<{ data: GoalRecord }>(`/api/goals/${id}?through=${through}`)).data); } catch(e) { close(); setError((e as Error).message); } } }
  function state(row: GoalRecord, status: keyof typeof statuses) { setActionError(""); setConfirmation({ title: `${status === "ACTIVE" ? "Reativar" : status === "COMPLETED" ? "Concluir" : "Arquivar"} meta?`, description: "O histórico será preservado. Metas encerradas podem ser reativadas para novas alterações.", url: `/api/goals/${row.id}`, method: "PATCH", body: { status } }); }
  async function confirm() { if (!confirmation || busy) return; setBusy(true); setActionError(""); try { await financialRequest(confirmation.url, { method: confirmation.method, body: confirmation.body ? JSON.stringify(confirmation.body) : undefined }); setConfirmation(null); if (confirmation.deleting) { close(); setMessage("Meta excluída definitivamente."); setPage(1); refresh(); } else await saved(); } catch(e) { setActionError((e as Error).message); } finally { setBusy(false); } }
  function removeGoal(row: GoalRecord) { setActionError(""); setConfirmation(row.canDelete ? { title: "Excluir meta?", description: "Esta ação excluirá permanentemente a meta e não poderá ser desfeita.", url: `/api/goals/${row.id}`, method: "DELETE", deleting: true } : { title: "Histórico preservado", description: "Esta meta possui histórico e não pode ser excluída definitivamente.", url: row.status !== "ARCHIVED" ? `/api/goals/${row.id}` : "", method: "PATCH", body: { status: "ARCHIVED" } }); }
  function actions(row: GoalRecord) { const items: RowAction[] = []; if (row.status === "ACTIVE") items.push({ label: "Editar", icon: Pencil, onSelect: () => edit(row, { kind: "goal" }) }, { label: "Adicionar contribuição", icon: Plus, onSelect: () => edit(row, { kind: "contribution" }) }, { label: "Concluir", icon: Check, onSelect: () => state(row, "COMPLETED") }); else items.push({ label: "Reativar", icon: RotateCcw, onSelect: () => state(row, "ACTIVE") }); if (row.status !== "ARCHIVED") items.push({ label: "Arquivar", icon: Archive, onSelect: () => state(row, "ARCHIVED") }); items.push({ label: "Excluir meta", icon: Trash2, danger: true, onSelect: () => removeGoal(row) }); return <RowActions description={row.name} items={items} />; }
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const p = new URLSearchParams(); for (const [k, v] of new FormData(event.currentTarget)) if (v) p.set(k, String(v)); setQuery(p.toString()); setPage(1); setFiltersOpen(false); refresh(); }
  const activeFilters = [...new URLSearchParams(query).keys()].length;
  const participants = (g: GoalRecord) => g.participants.length > 2 ? `${g.participants.length} participantes` : g.participants.map(p => p.name).join(" + ") || "Sem participantes";
  const common = { busy, setBusy, onDirty: setDirty, onSaved: saved, onCancel: requestClose };
  const Icon = (g: GoalRecord) => icons[g.icon as keyof typeof icons] ?? Target;
  return <><div className="page-heading"><div><span className="eyebrow">SEUS PLANOS, PASSO A PASSO</span><h1>Metas financeiras</h1><p>Acompanhe o que você está guardando para cada objetivo.</p></div><button className="button primary" disabled={loading || !!error} onClick={() => edit(null, { kind: "goal" })}><Plus size={18} />Nova meta</button></div><Feedback error={error} message={message} />
    <section className="panel goal-filters"><button type="button" className="goal-filter-toggle" aria-expanded={filtersOpen} aria-controls="goal-filters" onClick={() => setFiltersOpen(!filtersOpen)}><strong>Filtros e busca</strong><span>{new URLSearchParams(query).get("status") ? statuses[new URLSearchParams(query).get("status") as keyof typeof statuses] : "Todas as metas"} · {activeFilters} filtros aplicados <span aria-hidden="true">{filtersOpen ? "−" : "+"}</span></span></button>
      {filtersOpen && <form id="goal-filters" className="filters-grid" onSubmit={filter} key={query}><Select id="filter-status" label="Status" name="status" defaultValue={new URLSearchParams(query).get("status") ?? ""}><option value="">Todos</option>{Object.entries(statuses).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</Select><Field id="filter-search" label="Buscar nome" name="search" defaultValue={new URLSearchParams(query).get("search") ?? ""} maxLength={100} /><Field id="filter-participant" label="Participante" name="participant" defaultValue={new URLSearchParams(query).get("participant") ?? ""} maxLength={100} /><Select id="filter-account" label="Conta associada" name="accountId" defaultValue={new URLSearchParams(query).get("accountId") ?? ""}><option value="">Todas</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select><Select id="filter-deadline" label="Prazo" name="deadline" defaultValue={new URLSearchParams(query).get("deadline") ?? ""}><option value="">Todos</option><option value="NONE">Sem prazo</option><option value="OVERDUE">Prazo vencido</option><option value="UPCOMING">Prazo atual ou futuro</option></Select><DateField id="filter-through" label="Progresso até a competência" name="through" defaultValue={through} /><button className="button primary">Aplicar filtros</button><button type="button" className="button secondary" onClick={() => { setQuery(""); setPage(1); setFiltersOpen(false); refresh(); }}>Limpar filtros</button></form>}
    </section><p className="report-note">Progresso até {displayCompetence(through)}. Contribuições de competências futuras permanecem no histórico.</p>
    {loading ? <p role="status">Carregando metas…</p> : error ? <button className="button secondary" onClick={refresh}>Tentar novamente</button> : !result?.data.length ? <section className="panel empty-state">Nenhuma meta encontrada. Crie seu primeiro objetivo ou revise os filtros.</section> : <>
      <div className="ledger-desktop"><table className="ledger-table goal-ledger"><caption className="ledger-caption">Selecione a meta para ver os detalhes</caption><thead><tr>{["Meta", "Prazo", "Participantes", "Progresso", "Acumulado / Meta", "Status", "Ações"].map(v => <th key={v} scope="col" className={v === "Acumulado / Meta" ? "ledger-value" : undefined}>{v}</th>)}</tr></thead><tbody>{result.data.map(g => { const GoalIcon = Icon(g); return <tr key={g.id} onClick={() => setDetail(g)}><td><button className="ledger-description" onClick={e => { e.stopPropagation(); setDetail(g); }}><strong className="goal-name"><GoalIcon size={16} aria-hidden="true" />{g.name}</strong>{g.reached && <span>Meta atingida</span>}</button></td><td>{g.targetDate ? displayDate(g.targetDate) : "Sem prazo"}</td><td>{participants(g)}</td><td><GoalProgress value={g.progressPercentage} /></td><td className="ledger-value"><strong className="ledger-amount">{currency(g.totalContributed)}</strong><small className="goal-target">/ {currency(g.targetAmount)}</small></td><td><span className="ledger-status">{statuses[g.status]}</span></td><td><div className="ledger-actions">{actions(g)}</div></td></tr>; })}</tbody></table></div>
      <ul className="ledger-mobile advanced-mobile goal-mobile" aria-label="Metas financeiras">{result.data.map(g => <li key={g.id}><button className="ledger-mobile-entry" onClick={() => setDetail(g)}><span className="ledger-mobile-title">{g.name}</span><span className="ledger-status">{statuses[g.status]}</span><strong className="ledger-amount">{currency(g.totalContributed)} / {currency(g.targetAmount)}</strong><span className="ledger-mobile-date">{participants(g)} · {g.targetDate ? displayDate(g.targetDate) : "Sem prazo"}</span><GoalProgress value={g.progressPercentage} />{g.reached && <span className="ledger-mobile-date">Meta atingida</span>}</button>{actions(g)}</li>)}</ul>
    </>}
    {result && result.pagination.total > 0 && <nav className="pagination" aria-label="Paginação"><button className="button secondary" disabled={loading || page <= 1} onClick={() => { setPage(page - 1); setLoading(true); }}>Anterior</button><span>Página {page} de {Math.ceil(result.pagination.total / result.pagination.limit)}</span><button className="button secondary" disabled={loading || page * result.pagination.limit >= result.pagination.total} onClick={() => { setPage(page + 1); setLoading(true); }}>Próxima</button></nav>}
    {(detail || editor) && <Modal drawer dismissOutside busy={busy} title={editor ? editor.kind === "goal" ? detail ? "Editar meta" : "Nova meta" : editor.kind === "participant" ? "Participante" : "Contribuição" : detail!.name} onClose={requestClose}>
      {editor?.kind === "goal" ? <GoalForm initial={detail ?? undefined} accounts={accounts} {...common} /> : editor?.kind === "contribution" && detail ? <ContributionForm goal={detail} initial={editor.initial} accounts={accounts} {...common} /> : editor?.kind === "participant" && detail ? <ParticipantForm goal={detail} initial={editor.initial} {...common} /> : detail && <>
        <div className="goal-detail-summary"><p className="eyebrow">{statuses[detail.status]} · ATÉ {displayCompetence(detail.through)}</p><strong>{currency(detail.totalContributed)}</strong><p>Acumulado de {currency(detail.targetAmount)}</p><GoalProgress value={detail.progressPercentage} /><p>{detail.reached ? "Meta atingida" : `Faltam ${currency(detail.remainingAmount)}`}</p></div>
        <dl className="transaction-details ledger-details"><div><dt>Início</dt><dd>{displayDate(detail.startDate)}</dd></div><div><dt>Prazo</dt><dd>{detail.targetDate ? displayDate(detail.targetDate) : "Sem prazo"}</dd></div><div><dt>Situação do prazo</dt><dd>{detail.deadlineStatus}</dd></div><div><dt>Conta associada</dt><dd>{detail.account?.name ?? "Sem conta"}</dd></div></dl>
        {detail.suggestedMonthly && <p className="report-note">Referência mensal: <strong>{currency(detail.suggestedMonthly)}</strong>. Meses parciais contam como um mês. Orientação sem movimentação automática.</p>}{detail.description && <p className="transaction-notes">{detail.description}</p>}
        <div className="record-actions">{detail.status === "ACTIVE" ? <><button className="button primary" onClick={() => edit(detail, { kind: "contribution" })}><Plus size={16} />Adicionar contribuição</button><button className="button secondary" onClick={() => edit(detail, { kind: "goal" })}>Editar meta</button><button className="button secondary" onClick={() => state(detail, "COMPLETED")}>Concluir meta</button></> : <button className="button secondary" onClick={() => state(detail, "ACTIVE")}>Reativar meta</button>}{detail.status !== "ARCHIVED" && <button className="button secondary" onClick={() => state(detail, "ARCHIVED")}>Arquivar</button>}<button className="button secondary" onClick={() => removeGoal(detail)}>Excluir meta</button></div>
        <section className="goal-section"><h3>Participantes</h3><p className="report-note">Participações representam contribuições, sem divisão obrigatória ou dívida.</p><ul className="goal-history">{detail.participants.map(p => <li key={p.id}><div><strong>{p.name}{p.isActive ? "" : " (inativo)"}</strong><small>{currency(p.totalContributed)} · {p.percentage.replace(".", ",")}% do total</small></div>{detail.status === "ACTIVE" && <button className="button secondary" aria-label={`Editar participante ${p.name}`} onClick={() => edit(detail, { kind: "participant", initial: p })}>Editar</button>}</li>)}</ul>{!detail.participants.length && <p>Sem participantes cadastrados.</p>}{detail.status === "ACTIVE" && <button className="button secondary" onClick={() => edit(detail, { kind: "participant" })}>Adicionar participante</button>}</section>
        <section className="goal-section"><h3>Evolução por competência</h3><p className="report-note">Valores acumulados até {displayCompetence(detail.through)}.</p><ul className="goal-history">{detail.evolution.map(m => <li key={m.month}><span>{displayCompetence(m.month)}</span><strong>{currency(m.accumulated)}</strong></li>)}</ul>{!detail.evolution.length && <p>Sem contribuições no período.</p>}</section>
        <section className="goal-section"><h3>Contribuições</h3><ul className="goal-history">{detail.contributions.map(c => <li key={c.id}><div><strong>{currency(c.amount)}</strong><small>{displayDate(c.contributionDate)} · {detail.participants.find(p => p.id === c.participantId)?.name ?? "Sem participante"}</small><small>Competência {displayCompetence(c.competenceDate)}{c.competenceDate.slice(0,7) > detail.through.slice(0,7) ? " · Fora do período exibido" : ""}</small>{c.account && <small>{c.account.name}</small>}{c.transferId && <small>Transferência vinculada</small>}{c.description && <small>{c.description}</small>}</div>{detail.status === "ACTIVE" && <div className="goal-history-actions"><button className="button secondary" aria-label={`Editar contribuição de ${currency(c.amount)}`} onClick={() => edit(detail, { kind: "contribution", initial: c })}>Editar</button><button className="button secondary" aria-label={`Excluir contribuição de ${currency(c.amount)}`} onClick={() => { setActionError(""); setConfirmation({ title: "Excluir contribuição?", description: "O valor será removido do progresso da meta. A transferência vinculada, se existir, e os saldos das contas serão preservados.", url: `/api/goals/${detail.id}/contributions/${c.id}`, method: "DELETE" }); }}>Excluir</button></div>}</li>)}</ul>{!detail.contributions.length && <p>Ainda não há contribuições.</p>}</section>
      </>}
    </Modal>}
    {discardConfirmation}
    {confirmation && <Modal title={confirmation.title} busy={busy} onClose={() => setConfirmation(null)}><Feedback error={actionError} /><p>{confirmation.description}</p><div className="record-actions"><button className="button secondary" disabled={busy} onClick={() => setConfirmation(null)}>Cancelar</button>{confirmation.url && <button className={`button ${confirmation.deleting ? "danger" : "primary"}`} disabled={busy} onClick={confirm}>{confirmation.deleting ? "Excluir meta" : confirmation.title === "Histórico preservado" ? "Arquivar meta" : "Confirmar"}</button>}</div></Modal>}
  </>;
}
